defaultpage: /pages/ldserver.html
triplestore: http://localhost:9999/blazegraph/namespace/replicate/sparql
#triplestore: http://haproxy/blazegraph/sparql
SPARQLendpoint: sparql
base: http://donostia.eus/data
SPARQLRetrieveResourceQuery: DESCRIBE <{0}>
xslt: replicate.xsl
host: http://localhost:8080/ROOT/
#host: http://localhost:8080/data/



