defaultpage: /pages/ldserver.html
triplestore: http://localhost:9999/blazegraph/namespace/replicate/sparql
#triplestore: http://haproxy/blazegraph/sparql
SPARQLendpoint: sparql
base: http://donostia.eus/data
SPARQLretrieveResourceQuery: DESCRIBE <{0}>



